// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7l7FR6RG2WQUzLnQMHPoxgczGZenV3VM',
    appId: '1:58094377515:web:265d42c13d2ac57dab686e',
    messagingSenderId: '58094377515',
    projectId: 'develappers',
    authDomain: 'develappers.firebaseapp.com',
    storageBucket: 'develappers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCijo2-5KkoZQ3gOJZm0EZw7CjCI8_fc',
    appId: '1:58094377515:android:8105b17dbbd041beab686e',
    messagingSenderId: '58094377515',
    projectId: 'develappers',
    storageBucket: 'develappers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoohfVD0_QBdfvVKTUUuARzg-0iJ9SqmY',
    appId: '1:58094377515:ios:d21275e8d20def55ab686e',
    messagingSenderId: '58094377515',
    projectId: 'develappers',
    storageBucket: 'develappers.appspot.com',
    iosClientId: '58094377515-lra8hmsklnu0c5asu64rpolr2kph9b3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoohfVD0_QBdfvVKTUUuARzg-0iJ9SqmY',
    appId: '1:58094377515:ios:d21275e8d20def55ab686e',
    messagingSenderId: '58094377515',
    projectId: 'develappers',
    storageBucket: 'develappers.appspot.com',
    iosClientId: '58094377515-lra8hmsklnu0c5asu64rpolr2kph9b3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkpal',
  );
}
